services:
  - type: web
    name: newbiz-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

